# Generated by Django 3.1.5 on 2021-01-31 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Номер должен быть введён в формате Е.164.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('title', models.CharField(max_length=100, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('received_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('rcv', 'Получено'), ('prc', 'В обработке'), ('rpl', 'Ответ отправлен')], default='rcv', max_length=3)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
