# Generated by Django 3.1.5 on 2021-02-06 16:03

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teacher_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(default='teacher/avatar.png', upload_to=users.models.unique_file_name, verbose_name='Аватар'),
        ),
    ]
