# Generated by Django 3.1.5 on 2021-02-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210131_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
