# Generated by Django 3.1.5 on 2021-02-05 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('courses', '0004_auto_20210205_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='users.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='course_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='courses.coursegroup'),
        ),
    ]
