# Generated by Django 3.1.5 on 2021-02-13 10:02

from django.db import migrations
import easy_thumbnails.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210206_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='/static/images/course/image.png', upload_to=users.models.unique_file_name, verbose_name='Изображение'),
        ),
    ]
